#!/bin/sh
nodemon --ignore lib/config/user.json --ignore lib/config/cache.json --ignore lib/app/ui/ --ignore lib/sbc/ --ignore lib/app/public/ --ignore searchspring-sites/ --ignore springboard-library/ index.js

# sass --watch springboard.scss:../public/css/springboard.css --sourcemap
# webpack --progress --colors --watch
