#!/bin/sh
# code to run node with harmony flag for ecma6 support
# --expose_gc to expose the garbage collector global function gc()
nodemon --ignore lib/config/user.json --ignore lib/config/cache.json --ignore lib/app/ui/ --ignore lib/sbc/ --ignore lib/app/public/ --ignore searchspring-sites/ --ignore springboard-library/ index.js
